jobs:
  - name: demo-war-manifest
    type: manifest
    steps:
      - IN: demo-war
      - IN: demo-war-trg

  - name: demo-war-test-deploy
    type: deploy
    steps:
      - IN: demo-war-manifest
        force: true
      - IN: demo-war-test-cls
      - TASK:
        - script: sudo rm -rf /var/lib/tomcat7/webapps/*
        - script: sudo cp /tmp/shippable/demo-war-manifest/demo-war/sample.war /var/lib/tomcat7/webapps/sample.war

######################### BUILD AMI #########################
  - name: build-ami
    type: runSh
    steps:
      - IN: aws-creds
      - IN: bldami-repo
      - IN: bldami-params
      - TASK:
        - script: sudo apt-get install -y jq
        - script: IN/bldami-repo/gitRepo/basePack.sh bldami-params
    on_success:
      - script: echo "SUCCESS"
    on_failure:
      - script: cat /build/IN/bldami-repo/gitRepo/output.txt

############################ DEPLOY AWS INFRA #########################
#  - name: aws-infra-setup
#    type: runSh
#    steps:
#      - IN: aws-pem
#      - IN: aws-creds
#      - IN: setup-infra-repo
#      - TASK:
#        - script: sudo apt-get install -y jq
#        - script: IN/setup-infra-repo/gitRepo/build.sh
#    on_success:
#      - script: /build/IN/setup-infra-repo/gitRepo/archiveState.sh
#    on_failure:
#      - script: /build/IN/setup-infra-repo/gitRepo/archiveState.sh
#
#  - name: test-infra-prov
#    type: runSh
#    steps:
#      - IN: aws-pem
#      - IN: aws-creds
#      - IN: test-infra-repo
#      - IN: aws-infra-setup
#      - IN: build-ami
#        switch: off
#      - TASK:
#        - script: sudo apt-get install -y jq
#        - script: IN/test-infra-repo/gitRepo/build.sh
#    on_success:
#      - script: /build/IN/test-infra-repo/gitRepo/archiveState.sh
#    on_failure:
#      - script: /build/IN/test-infra-repo/gitRepo/archiveState.sh
#
#  - name: prod-infra-prov
#    type: runSh
#    steps:
#      - IN: aws-pem
#      - IN: aws-creds
#      - IN: prod-infra-repo
#      - IN: aws-infra-setup
#      - IN: build-ami
#        switch: off
#      - TASK:
#        - script: sudo apt-get install -y jq
#        - script: IN/prod-infra-repo/gitRepo/build.sh
#    on_success:
#      - script: /build/IN/prod-infra-repo/gitRepo/archiveState.sh
#    on_failure:
#      - script: /build/IN/prod-infra-repo/gitRepo/archiveState.sh

########################## API PIPELINE JOBS #########################
## manifest gen for API
#  - name: api-man
#    type: manifest
#    steps:
#      - IN: micro-api-img
#      - IN: api-img-opts
#      - IN: test-infra-prov
#
## TEST deployment for API
#  - name: api-test
#    type: deploy
#    steps:
#      - IN: api-man
#      - IN: env-test-aws
#      - TASK: managed
#
## PROD deployment for API
#  - name: api-prod
#    type: deploy
#    steps:
#      - IN: sit
#      - IN: api-p-scaler
#      - IN: api-test
#        switch: off
#      - IN: env-prod-aws
#      - TASK: managed
#
######################### SIT JOBS #########################
#  - name: sit
#    type: runSh
#    steps:
#      - IN: sit-repo
#      - IN: api-test
#      - IN: sit-params
#      - TASK:
#        - script: sudo apt-get install -y jq
#        - script: IN/sit-repo/gitRepo/test.sh sit-params
#    on_success:
#      - script: touch /build/state/success.txt
#    on_failure:
#      - script: touch /build/state/failure.txt
